version: '3.5'

x-redis-socket:
  &redis-socket
  type: bind
  source: ./sockets/redis
  target: /run/redis-openvas

services:
  openvas-docker:
    build:
      context: .
      dockerfile: Docker/openvas.dockerfile
    image: openvas-docker
    tty: true
    depends_on:
      - openvas-redis
    volumes:
      - <<: *redis-socket

  openvas-redis:
    build:
      context: .
      dockerfile: Docker/redis.dockerfile
    volumes:
      - <<: *redis-socket

